"""rebuit the mkodels properly 

Revision ID: 63e6aad415e1
Revises: 
Create Date: 2026-07-18 16:12:37.768126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63e6aad415e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('class_name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('class_name'),
    sa.UniqueConstraint('class_name')
    )
    op.create_table('exam',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('exam_name', sa.String(length=50), nullable=False),
    sa.Column('academic_year', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('exam_id')
    )
    op.create_table('staff',
    sa.Column('staff_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PRINCIPAL', 'TEACHER', name='staff_roles_constraints'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('profile_pic', sa.String(length=100), nullable=True),
    sa.Column('admin_remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('staff_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('subjects',
    sa.Column('subject_id', sa.String(length=15), nullable=False),
    sa.Column('subject_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_table('class_teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=10), nullable=False),
    sa.Column('staff_id', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['class_name'], ['classes.class_name'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_name'),
    sa.UniqueConstraint('staff_id')
    )
    op.create_table('principal',
    sa.Column('staff_id', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.create_table('student',
    sa.Column('admission_no', sa.String(length=10), nullable=False),
    sa.Column('roll_no', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('academic_year', sa.String(length=10), nullable=True),
    sa.Column('class_name', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['class_name'], ['classes.class_name'], ),
    sa.PrimaryKeyConstraint('admission_no'),
    sa.UniqueConstraint('admission_no'),
    sa.UniqueConstraint('class_name', 'roll_no', 'academic_year', name='unique_roll_per_class'),
    sa.UniqueConstraint('roll_no')
    )
    op.create_table('teacherassigned',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.String(length=10), nullable=False),
    sa.Column('class_name', sa.String(length=10), nullable=False),
    sa.Column('subject_id', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['class_name'], ['classes.class_name'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_name', 'subject_id', name='unique_per_class')
    )
    op.create_table('marks',
    sa.Column('mark_id', sa.Integer(), nullable=False),
    sa.Column('admission_no', sa.String(length=10), nullable=False),
    sa.Column('subject_id', sa.String(length=15), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('marks_obtained', sa.Float(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admission_no'], ['student.admission_no'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.exam_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('mark_id'),
    sa.UniqueConstraint('admission_no', 'exam_id', 'subject_id', name='unique_student_marks')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marks')
    op.drop_table('teacherassigned')
    op.drop_table('student')
    op.drop_table('principal')
    op.drop_table('class_teacher')
    op.drop_table('subjects')
    op.drop_table('staff')
    op.drop_table('exam')
    op.drop_table('classes')
    # ### end Alembic commands ###
